ServerEvents.tags("item", (event) => {
	event.add(
		"c:stripped_logs",
		"biomesoplenty:stripped_fir_log",
		"biomesoplenty:stripped_pine_log",
		"biomesoplenty:stripped_maple_log",
		"biomesoplenty:stripped_redwood_log",
		"biomesoplenty:stripped_mahogany_log",
		"biomesoplenty:stripped_jacaranda_log",
		"biomesoplenty:stripped_palm_log",
		"biomesoplenty:stripped_willow_log",
		"biomesoplenty:stripped_dead_log",
		"biomesoplenty:stripped_magic_log",
		"biomesoplenty:stripped_umbran_log",
		"biomesoplenty:stripped_hellbark_log",
		"biomesoplenty:stripped_empyreal_log",
		"croptopia:stripped_cinnamon_log",
		"deeperdarker:stripped_echo_log",
		"extradelight:stripped_cinnamon_log",
		"extradelight:stripped_fruit_log",
		"biomeswevegone:stripped_palo_verde_log"
	);
	event.add(
		"c:stripped_woods",
		"biomesoplenty:stripped_fir_wood",
		"biomesoplenty:stripped_pine_wood",
		"biomesoplenty:stripped_maple_wood",
		"biomesoplenty:stripped_redwood_wood",
		"biomesoplenty:stripped_mahogany_wood",
		"biomesoplenty:stripped_jacaranda_wood",
		"biomesoplenty:stripped_palm_wood",
		"biomesoplenty:stripped_willow_wood",
		"biomesoplenty:stripped_dead_wood",
		"biomesoplenty:stripped_magic_wood",
		"biomesoplenty:stripped_umbran_wood",
		"biomesoplenty:stripped_hellbark_wood",
		"biomesoplenty:stripped_empyreal_wood",
		"croptopia:stripped_cinnamon_wood",
		"deeperdarker:stripped_echo_wood",
		"extradelight:strippedcinnamon_wood",
		"extradelight:stripped_fruit_wood",
		"biomeswevegone:stripped_palo_verde_wood"
	);
});
