pack:forgeworks:
  - "### Which (package|modpack) is this (bug report|feature request|mod request) for\\?\\n\\nforgeworks\\n"
pack:minigames:
  - "### Which (package|modpack) is this (bug report|feature request|mod request) for\\?\\n\\nminigames\\n"
