- name: "type:mod"
  description: "This issue or PR requests for or adds a mod"
  color: "2c4175"
- name: "type:bug"
  description: "This issue reports a bug"
  color: "ae120d"
- name: "type:bugfix"
  description: "This PR fixes a bug"
  color: "ed760e"
- name: "type:feature"
  description: "This issue or PR request for or adds a feature"
  color: "20dca9"
- name: "status:needs testing"
  description: "This bugfix needs to be tested"
  color: "900C3F"
- name: "status:blocked"
  description: "This issue or PR is blocked"
  color: "763C28"
- name: "bug:unverified"
  description: "This bug report still needs to be verified"
  color: "750606"
- name: "bug:confirmed"
  description: "This bug report has been verified"
  color: "670a0a"
- name: "pack:forgeworks"
  description: "This issue or PR is related to the Forgeworks modpack"
  color: "f0a500"
- name: "pack:minigames"
  description: "This issue or PR is related to the Minigames KubeJS pack"
  color: "f0a500"
