name: Bug Report
description: "Submit a bug report for the server or one of it's mods."
assignees: ["jaronz"]
labels: ["type: bug"]
title: "[FIX] "

body:
  - type: dropdown
    id: package
    attributes:
      label: Which package is this bug report for?
      options:
        - forgeworks
        - minigames
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
