name: Bug Report
description: "Submit a bug report for the server or one of it's mods."
assignees: ["jaronz"]
type: Bug
title: "[FIX] "

body:
  - type: textarea
    attributes:
      label: Bug
      description: Describe the bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true