name: Feature Request
description: "Submit a request for a feature to be added to the server."
assignees: ["jaronz"]
type: Feature
title: "[FEAT] "

body:
  - type: markdown
    attributes:
      value: |
        Thank you for considering contributing to this project! Please provide a detailed description of the feature you would like to see implemented.

  - type: checkboxes
    id: new-issue
    attributes:
      label: Is there an existing issue or pull request for this feature request?
      description: Before submitting a new feature request, please check if there is already an open issue or pull request for this feature.
      options:
        - label: There are no existing issues or pull requests for this feature request.
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Describe the feature you would like to see implemented in detail.
      placeholder: Please provide a detailed description of the problem you are trying to solve or the feature you would like to see implemented.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired solution
      description: Describe the solution you would like to see implemented.
      placeholder: Please provide a detailed description of the solution you would like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Considered alternatives
      description: Describe any alternative solutions you have considered.
      placeholder: Please provide a detailed description of any alternative solutions you have considered.
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any other information that might be relevant to the feature request.
      placeholder: Include any context, use cases, or other information that might help in understanding the feature request.
    validations:
      required: false
